services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: businessmanagement-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#piruobando2691
      - MSSQL_PID=Express
    ports:
      - "14333:1433"
    networks:
      - businessmanagement-net

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: businessmanagement-webapi
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BusinessManagementDB;User Id=sa;Password=#piruobando2691;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - businessmanagement-net

networks:
  businessmanagement-net:
