name: .NET Build, Test, and Docker Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal BusinessManagement.UnitTests/BusinessManagement.UnitTests.csproj

    # Add Docker steps below, only run on push to main.
    - name: Log in to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: 26jeanca
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          26jeanca/businessmanagement-webapi:latest
          26jeanca/businessmanagement-webapi:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 